apiVersion: core.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  name: observatorium-xyz
  namespace: <namespace>
  labels:
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-cr
    app.kubernetes.io/part-of: observatorium
spec:
  store:
    cache:
      exporterImage: 'prom/memcached-exporter:v0.6.0'
      exporterVersion: v0.6.0
      image: 'docker.io/memcached:1.6.3-alpine'
      memoryLimitMb: 1024
      replicas: 1
      version: 1.6.3-alpine
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    shards: 1
    version: master-2020-08-12-70f89d83
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  loki:
    image: 'docker.io/grafana/loki:2.1.0'
    replicas:
      distributor: 1
      ingester: 3
      querier: 3
      query_frontend: 3
      table_manager: 1
    version: 2.1.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
  compact:
    enableDownsampling: false
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    replicas: 1
    retentionResolution1h: 1s
    retentionResolution5m: 1s
    retentionResolutionRaw: 14d
    version: master-2020-08-12-70f89d83
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  receivers:
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    replicas: 1
    version: master-2020-08-12-70f89d83
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  query:
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    replicas: 1
    version: master-2020-08-12-70f89d83
  apiQuery:
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    version: master-2020-08-12-70f89d83
  hashrings:
    - hashring: default
      tenants: []
  thanosReceiveController:
    image: 'quay.io/observatorium/thanos-receive-controller:master-2020-02-06-b66e0c8'
    version: master-2020-02-06-b66e0c8
  api:
    image: 'quay.io/observatorium/observatorium:master-2020-11-02-v0.1.1-192-ge324057'
    rbac:
      roleBindings:
        - name: tenant1
          roles:
            - tenant1
          subjects:
            - kind: user
              name: tenant1@example.com
        - name: tenant2
          roles:
            - tenant2
          subjects:
            - kind: user
              name: admin@example.com
      roles:
        - name: tenant1
          permissions:
            - read
            - write
          resources:
            - logs
            - metrics
          tenants:
            - tenant1
        - name: tenant2
          permissions:
            - read
            - write
          resources:
            - logs
            - metrics
          tenants:
            - tenant2
    replicas: 1
    tenants:
      - id: 1610b0c3-c509-4592-a256-a1871353dbfa
        name: tenant1
        oidc:
          clientID: tenant1
          clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
          issuerURL: 'http://dex.dex.svc.cluster.local:5556/dex'
          usernameClaim: email
      - id: b10586b6-6ef5-4e40-a4eb-6b37447ee5cc
        name: tenant2
        oidc:
          clientID: tenant2
          clientSecret: dGVuYW50Mi1wYXNzCg==
          issuerURL: 'http://dex.dex.svc.cluster.local:5556/dex'
          usernameClaim: email
    tls:
      caKey: ca.pem
      certKey: cert.pem
      configMapName: observatorium-xyz-tls
      keyKey: key.pem
      secretName: observatorium-xyz-tls
      serverName: observatorium-xyz-observatorium-api.observatorium.svc.cluster.local
    version: latest
  queryFrontend:
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    replicas: 1
    version: master-2020-08-12-70f89d83
  rule:
    image: 'quay.io/thanos/thanos:master-2020-08-12-70f89d83'
    replicas: 1
    version: master-2020-08-12-70f89d83
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  objectStorageConfig:
    loki:
      accessKeyIdKey: aws_access_key_id
      bucketsKey: buckets
      endpointKey: endpoint
      regionKey: region
      secretAccessKeyKey: aws_secret_access_key
      secretName: loki-objectstorage
    thanos:
      key: thanos.yaml
      name: thanos-objectstorage
