---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: proxy-console-ui
parameters:
  - name: NGINX_IMAGE
    value: quay.io/app-sre/ubi8-nginx-118
    required: true
  - name: CONSOLE_UI_URL
    value: https://console.redhat.com/
    required: true
  - name: PROXY_SSO_URL
    required: true
objects:

  # Nginx proxy to dispatch UI requests to the correct micro frontend or
  # fallback to the CONSOLE_UI_URL
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: proxy-console-ui
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: proxy-console-ui
      template:
        metadata:
          labels:
            app: proxy-console-ui
        spec:
          containers:
            - name: proxy
              image: ${NGINX_IMAGE}
              command:
                - nginx
                - -g
                - "daemon off;"
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: config
                  mountPath: /opt/app-root/etc/nginx.default.d/proxy.conf
                  subPath: proxy.conf
              imagePullPolicy: Always
          volumes:
            - name: config
              configMap:
                name: proxy-console-ui-config
          restartPolicy: Always
          terminationGracePeriodSeconds: 30

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: proxy-console-ui-config
    data:
      proxy.conf: |-
        location /application-services {
          proxy_pass http://application-services-ui:80/;
        }
        location /apps/application-services {
          proxy_pass http://application-services-ui:80/;
        }
        location /beta/application-services {
          proxy_pass http://application-services-ui:80/;
        }
        location /beta/apps/application-services {
          proxy_pass http://application-services-ui:80/;
        }

        location / {
          proxy_ssl_server_name on;
          proxy_set_header  Accept-Encoding "";
          proxy_pass        ${CONSOLE_UI_URL};

          sub_filter        'https://sso.qa.redhat.com' '${PROXY_SSO_URL}';
          sub_filter_once   off;
          sub_filter_types  application/x-javascript;
        }

  - apiVersion: v1
    kind: Service
    metadata:
      name: proxy-console-ui
    spec:
      selector:
        app: proxy-console-ui
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
