apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: <namespace>
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app.kubernetes.io/name: minio
  sessionAffinity: None
  type: ClusterIP