apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kas-fleetshard-agent
  labels:
    app: mas-sso
spec:
  realmSelector:
    matchLabels:
      app: rhoas
  client:
    clientId: kas-fleetshard-agent
    secret: kas-fleetshard-agent
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    serviceAccountsEnabled: true
    standardFlowEnabled: false
    attributes:
          "kas-fleetshard-operator-cluster-id": "2ieq35mpf26sq2r246sbffuvg9s380sp"
    protocolMappers:
    - name: kas-fleetshard-operator-cluster-id
      protocol: openid-connect
      protocolMapper: oidc-usermodel-attribute-mapper
      consentRequired: false
      config:
        userinfo.token.claim: 'true'
        user.attribute: kas-fleetshard-operator-cluster-id
        id.token.claim: 'true'
        access.token.claim: 'true'
        claim.name: kas-fleetshard-operator-cluster-id
        jsonType.label: String
    access: 
       view: true
       configure: true
       manage: true

     