---
apiVersion: v1
kind: Template
metadata:
  name: kas-cluster-owner
parameters:
- name: RH_USERNAME
  required: true
- name: RH_USER_ID
  required: true
- name: RH_ORG_ID
  required: true
objects:
- apiVersion: keycloak.org/v1alpha1
  kind: KeycloakUser
  metadata:
    name: kas-cluster-owner
    labels:
      app: mas-sso
  spec:
    realmSelector:
      matchLabels:
        app: rhoas
    user:
      username: ${RH_USERNAME}
      credentials:
      - type: "password"
        value: "${RH_USERNAME}"
      enabled: True
      clientRoles:
        'realm-management': [ 'view-users' ]
      attributes:
        "rh-user-id": [ "${RH_USER_ID}" ]
        "rh-org-id": [ "${RH_ORG_ID}" ]
        "preferred_username": [ "${RH_USERNAME}" ]
      access:
         view: true
         configure: true
         manage: true
- apiVersion: keycloak.org/v1alpha1
  kind: KeycloakClient
  metadata:
    name: kas-cluster-owner-client
    labels:
      app: mas-sso
  spec:
    realmSelector:
      matchLabels:
        app: rhoas
    client:
      clientId: ${RH_USERNAME}
      secret: ${RH_USERNAME}
      clientAuthenticatorType: client-secret
      protocol: openid-connect
      serviceAccountsEnabled: false
      standardFlowEnabled: false
      directAccessGrantsEnabled: true
      protocolMappers:
      - name: rh-user-id
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: rh-user-id
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: rh-user-id
          jsonType.label: String
      - name: rh-org-id
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: rh-org-id
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: rh-org-id
          jsonType.label: String
      - name: preferred_username
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: preferred_username
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: preferred_username
          jsonType.label: String
      access:
         view: true
         configure: true
         manage: true
