apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: strimzi-ui
  labels:
    app: mas-sso
spec:
  realmSelector:
    matchLabels:
      app: rhoas
  client:
    clientId: strimzi-ui
    protocol: openid-connect
    publicClient: true
    standardFlowEnabled: true
    redirectUris: ["*"]
    webOrigins: ["*"]
    protocolMappers:
      - name: account-id
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: account-id
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: account_id
          jsonType.label: String
      - name: rh-user-id
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: rh-user-id
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: rh-user-id
          jsonType.label: String
      - name: rh-org-id
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: rh-org-id
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: rh-org-id
          jsonType.label: String
      - name: preferred_username
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          user.attribute: preferred_username
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: preferred_username
          jsonType.label: String
      - name: is_org_admin
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          userinfo.token.claim: 'true'
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: is_org_admin
          claim.value: 'true'
          jsonType.label: boolean
