apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: strimzi-ui
  labels:
    app: mas-sso
spec:
  realmSelector:
    matchLabels:
      app: rhoas
  client:
    clientId: strimzi-ui
    protocol: openid-connect
    publicClient: true
    standardFlowEnabled: true
    redirectUris: ["*"]
    webOrigins: ["*"]

    

     