apiVersion: v1
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBdTCCARqgAwIBAgIUQ01v4IujQzwxqSRgTBFO4JV6YMowCgYIKoZIzj0EAwIw
    GDEWMBQGA1UEAxMNb2JzZXJ2YXRvcml1bTAeFw0yMDA5MDQxMDQ2MDBaFw0yNTA5
    MDMxMDQ2MDBaMBgxFjAUBgNVBAMTDW9ic2VydmF0b3JpdW0wWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAAS4xlNPCuLCt4+RPdy/fp9FewRPiCe1I/dFxfVFbi+XWPAK
    UtVe4DRlZ6aPECfwuF8KFC/s9KTiTKQzidQ4ZuM/o0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUGBctmqGA7gDy9TSc43+7Whh1
    HGEwCgYIKoZIzj0EAwIDSQAwRgIhAK0hPTmDdKAf4pRt7KJbXZx/a0I3hYhuy1+S
    d5O5saTZAiEA4zSyUZFO/+oKA2YvgvyfBvBUlehdCOd868GwWmn46NA=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: observatorium-xyz-tls
  namespace: <namespace>